/**
 * _SDS_ServerImplBase.java
 * Generated by the IDL-to-Java compiler (portable), version "3.0"
 * from SDS_Server.idl
 * Mittwoch, 27. Juni 2001 19.08 Uhr GMT+02:00
 */

public abstract class _SDS_ServerImplBase extends org.omg.CORBA.portable.ObjectImpl
        implements SDS_Server, org.omg.CORBA.portable.InvokeHandler {

    private static java.util.Hashtable _methods = new java.util.Hashtable();

    static {
        _methods.put("investigate", new java.lang.Integer(0));
    }

    // Type-specific CORBA::Object operations
    private static String[] __ids = {
            "IDL:SDS_Server:1.0"};

    // Constructors
    public _SDS_ServerImplBase() {
    }

    public org.omg.CORBA.portable.OutputStream _invoke(String method,
                                                       org.omg.CORBA.portable.InputStream in,
                                                       org.omg.CORBA.portable.ResponseHandler rh) {
        org.omg.CORBA.portable.OutputStream out = null;
        java.lang.Integer __method = (java.lang.Integer) _methods.get(method);
        if (__method == null)
            throw new org.omg.CORBA.BAD_OPERATION(0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

        switch (__method.intValue()) {
            case 0:  // SDS_Server/investigate
            {
                String name = in.read_string();
                SDS_ServerPackage.Reply __result = null;
                __result = this.investigate(name);
                out = rh.createReply();
                SDS_ServerPackage.ReplyHelper.write(out, __result);
                break;
            }

            default:
                throw new org.omg.CORBA.BAD_OPERATION(0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
        }

        return out;
    } // _invoke

    public String[] _ids() {
        return __ids;
    }


} // class _SDS_ServerImplBase
