
/**
* SDS_ServerOperations.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from SDS_Server.idl
* Mittwoch, 27. Juni 2001 19.08 Uhr GMT+02:00
*/

public interface SDS_ServerOperations 
{
  SDS_ServerPackage.Reply investigate (String name);
} // interface SDS_ServerOperations
