package SDS_ServerPackage;

/**
 * SDS_ServerPackage/ReplyHolder.java
 * Generated by the IDL-to-Java compiler (portable), version "3.0"
 * from SDS_Server.idl
 * Mittwoch, 27. Juni 2001 19.08 Uhr GMT+02:00
 */

public final class ReplyHolder implements org.omg.CORBA.portable.Streamable {
    public SDS_ServerPackage.Reply value = null;

    public ReplyHolder() {
    }

    public ReplyHolder(SDS_ServerPackage.Reply initialValue) {
        value = initialValue;
    }

    public void _read(org.omg.CORBA.portable.InputStream i) {
        value = SDS_ServerPackage.ReplyHelper.read(i);
    }

    public void _write(org.omg.CORBA.portable.OutputStream o) {
        SDS_ServerPackage.ReplyHelper.write(o, value);
    }

    public org.omg.CORBA.TypeCode _type() {
        return SDS_ServerPackage.ReplyHelper.type();
    }

}
